### ISSUE TITLE
ModuleNotFoundError: No module named 'fastapi'

### ISSUE THREAD

**Issue by shlyamster** [Lancetnik/Propan#87]
When installing Propan without an optional `doc`, an error occurs when there is no `fastapi`.

Install cmd: `python -m pip install propan[async-rabbit]`
Propan version: `0.1.4.1`

```bash
Traceback (most recent call last):
  File ".../.venv/bin/propan", line 5, in <module>
    from propan.__main__ import cli
  File ".../.venv/lib/python3.9/site-packages/propan/__init__.py", line 3, in <module>
    from propan.brokers import PropanMessage
  File ".../.venv/lib/python3.9/site-packages/propan/brokers/__init__.py", line 1, in <module>
    from propan.brokers._model.schemas import PropanMessage
  File ".../.venv/lib/python3.9/site-packages/propan/brokers/_model/__init__.py", line 1, in <module>
    from propan.brokers._model.broker_usecase import BrokerUsecase
  File ".../.venv/lib/python3.9/site-packages/propan/brokers/_model/broker_usecase.py", line 31, in <module>
    from propan.brokers._model.schemas import BaseHandler, PropanMessage
  File ".../.venv/lib/python3.9/site-packages/propan/brokers/_model/schemas.py", line 10, in <module>
    from propan._compat import get_model_fileds, model_schema, update_model_example
  File ".../.venv/lib/python3.9/site-packages/propan/_compat.py", line 7, in <module>
    from fastapi import __version__ as FASTAPI_VERSION
ModuleNotFoundError: No module named 'fastapi'
```

**Comment by Lancetnik** [comment]
@shyamster  appreciate your Issue! I hope, this package was helpful for u? Can you please tell some words about your case and experience with **Propan**?

**Comment by shlyamster** [comment]
@Lancetnik I use Propan in two variations: a dependency for publishing messages from the `sanic` backend or a cli app processing these very messages. In the case of a cli application, there are naturally no dependencies on backend frameworks.
